# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mathias Schilling
title: Data Scientist, Systems Engineer, Algorithm Specialist
email: mathias.schilling 'at' gmx.ch
website: https://github.com/mathiasschilling

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: mathiasschilling
github_username:  mathiasschilling
# stackoverflow_username: "00000001"
# dribbble_username: mathiasschilling
# facebook_username: mathiasschilling
# flickr_username: mathiasschilling
#instagram_username: mathiasschilling
linkedin_username: mathias-schilling
# xing_username: mathiasschilling
# pinterest_username: mathiasschilling
#youtube_username: mathiasschilling
# googleplus_username: +mathiasschilling
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  I'm a passionate algorithm developer and data scientist with a keen interest in applying technology to solve real-world problems. With a background in systems engineering, I bring a unique perspective to the intersection of data science, applied machine learning, RAG and data-driven analysis and modeling. With a keen eye on the latest advancements in machine learning, my professional such as private projects reflect my passion to innovative approaches in optimizing processes through the power of LLMs and data-driven insights.

content:

  - title: Skills
    layout: list
    content:
      - layout: left
        #title: Skills
        description: |
          - Python, Matlab, R, C++
          - Data mining and visualization
          - Experience with ML/DL frameworks in Python (TensorFlow, Scikit-Learn)
          - Application of GenAI models (OpenAI API, llama-cpp, ollama, stable-diffusion)
          - PoC of custom RAG applications (langchain, custom embeddings, VectorDB, prompt augmentation and tuning)
          - Cloud computing in Microsoft Azure
          - ETL, MySQL

  - title: Public Projects
    layout: list
    content:
      - layout: top-middle
        title: AB-Test Using Generated Personas and LLMs
        link: https://github.com/mathiasschilling/A-B-Test-Using-Generated-Personas-and-LLMs
        quote: >
          Quickly create surveys about which contentet is preferred using personas and LLMs.
        description: |
          This project demonstates fast and extensive comparison and evaluation possibilities of two sets of content items <mark>A</mark> and <mark>B</mark> by A/B testing means using generated personas in combination with large language models (LLMs). For demonstration purposes, job descriptions are used. Fittingly, as for personas, gratuates of different fields of study are created.
          
          Of course, the scope of such comparisons is not limited to job descriptions. With slight modifications, images such as landing sites and design choices can be compared quite easily and extensively, e.g. using GPT Vision.
          
      - layout: top-middle
        title: Paragliding Tracker
        link: https://github.com/mathiasschilling/ParaglidingTracker
        quote: >
          Visualize and analyze your own paragliding flights.
        description: |
          This R script is developed to analyze and visualize paragliding flight data, e.g. from Skytraxx variometer records. It processes data sets including altitude, longitude, and latitude, offering useful analytics to understand paragliding patterns and behaviors.

  - title: Work Experience # Title for the section
    layout: list
    content:
      - layout: left
        title: Algorithm Specialist, Data Scientist (Metrohm AG)
        caption: 2022 - today
        description: |
          - Development and deployment of algorithms for multivariate regression and classification.
          - Design and training of neural networks for regression and object classification.
            
      - layout: left
        title: Systems Engineer, Development of New Spectroscopic Systems (Metrohm AG)
        link: https://youtu.be/Wuio7pqlPf0
        caption: 2017 - 2022
        description: |
          - Development of various NIR spectroscopy systems from the conceptual phase to release.
          - Main focus on numerical methods for multivariate data analysis.
          - Engaged in requirements engineering and testing.
          - Development of a temperature-stable instrument calibration scheme.
            
      - layout: left
        title: Applications Specialist Spectroscopy (Metrohm AG)
        caption: 2016 - 2017
        description: |
          - Conducting feasibility studies for NIR analytical systems.
          - Creating marketing material for the systems.
          - Providing training on the use and application of NIR analytical systems.

  - title: Education # Title for the section
    layout: list
    content:
      - layout: left
        title: MAS Data Science
        #link: https://opg.optica.org/ao/fulltext.cfm?uri=ao-56-14-4076&id=363687
        caption: 2022 - 2024
        #sub_title: MSc Chemistry for the Life Sciences
        description: |
          - Proficient in data description and graphical representation using R and Python.
          - Competent in statistical models, hypothesis testing, confidence intervals, and regression analysis with R.
          - Skilled in clustering and classification, including kNN, classification trees, and random forests.
          - Foundational Python scripting abilities and proficiency in SQL for data manipulation and warehousing.
          - Experienced with Big Data tools like Apache Hadoop and Spark, and in executing large-volume data projects.
          - Capable of advanced regression modeling, network analysis, and data enhancement and processing with R and Python.
          - Knowledgeable in machine learning and deep learning principles, selecting appropriate techniques and developing models with TensorFlow in Python.
          - Proficient in advanced data science techniques including Retrieval-Augmented Generation (RAG), computer vision, and advanced statistical evaluation with R. 
          
      - layout: left
        title:  MSc Chemistry for the Life Sciences
        link: https://opg.optica.org/ao/fulltext.cfm?uri=ao-56-14-4076&id=363687
        caption: 2008 - 2016
        #sub_title:
        description: |
          - Investigation of emergence of multimodulation artifacts in FT-IR spectroscopy.
          - Development of a demodulation scheme of interferograms reducing the artifacts.

         

  - title: A Little More About Me
    layout: list
    content:

      - layout: left
        title: Other Hobbies
        description: |
          Alongside my interests in data science, machine learning, RAG and automation, some of my other interests and hobbies are:
          - Paragliding
          - Bouldering
          - Running
          - Baking
          - ProjectEuler


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
